services:
  timescope-frontend:
    build:
      context: TimeScope.Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./TimeScope.Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
